blank_issues_enabled: false
contact_links:
  - name: 💬 Questions & ideas
    url: https://github.com/ik-labs/perch/discussions
    about: For general questions and open-ended discussion, please use Discussions.
